-- SQLite
CREATE TABLE Hitters (
    ID TEXT UNIQUE NOT NULL,
    Name TEXT NOT NULL,
    G INTEGER NOT NULL,
    PA INTEGER NOT NULL,
    AB INTEGER NOT NULL,
    R INTEGER NOT NULL,
    H INTEGER NOT NULL,
    Doubles INTEGER NOT NULL,
    Triples INTEGER NOT NULL,
    HR INTEGER NOT NULL,
    RBI INTEGER NOT NULL,
    SB INTEGER NOT NULL,
    CS INTEGER NOT NULL,
    BB INTEGER NOT NULL,
    SO INTEGER NOT NULL,
    TB INTEGER NOT NULL,
    GDP INTEGER NOT NULL,
    HBP INTEGER NOT NULL,
    SH INTEGER NOT NULL,
    SF INTEGER NOT NULL,
    IBB INTEGER NOT NULL
)