-- SQLite
CREATE TABLE Players (
    ID TEXT UNIQUE NOT NULL,
    Name TEXT NULL,
    G INTEGER NULL,
    GS INTEGER NULL,
    MP INTEGER NULL,
    FG INTEGER NULL,
    FGA INTEGER NULL,
    Threes INTEGER NULL,
    ThreesAttempted INTEGER NULL,
    Twos INTEGER NULL,
    TwosAttempted INTEGER NULL,
    FT INTEGER NULL,
    FTA INTEGER NULL,
    ORB INTEGER NULL,
    DRB INTEGER NULL,
    AST INTEGER NULL,
    STL INTEGER NULL,
    BLK INTEGER NULL,
    Turnovers INTEGER NULL,
    PF INTEGER NULL,
    PTS INTEGER NULL
)